flowchart TD
    Title[Encounter Hierarchy] --> Organ{Are you over organed?}
    Organ --> |Yes| Liver[Zone set to Drunken Stupor]
    Organ --> |No| HardCoded

    subgraph "Organ Failure Zone"
        Liver[Zone set to Drunken Stupor] -->
        Stomach[Zone set to Bloated and Nauseous] -->
        Spleen[Zone set to Poisoned Liver]
        Liver -.- SSPD[If St. Sneaky Pete's Day and drunkenness 26+, receive SSPD Stupor]
    end
    Spleen --> HardCoded
    HardCoded{Hard-Coded?}
    HardCoded --> |Yes| Encounter
    HardCoded --> |No| PortScan

    subgraph "Zone Overrides"
        ZoneOverrideNote["Not a &quot;true&quot; wandering monster.<br>This is a special exception that has higher priority"]
        PortScan[Port Scan] 
    end
    PortScan --> AstralMushroom

    AstralMushroom{"Flashbacks<br />(Astral Mushrooms)"} --> |Yes| Encounter
    AstralMushroom --> |No| MiniAdventurer

    MiniAdventurer{"Littlest Identity Crisis<br />(Mini-Adventurer)"} --> |Yes| Encounter
    MiniAdventurer --> |No| LlamaLama

    LlamaLama{"Welcome Back<br />(Llama Lama Gong)"} --> |Yes| Encounter
    LlamaLama --> |No| Lucky

    Lucky{"Lucky"} --> |Yes| Encounter
    Lucky --> |No| Hallowiener

    Hallowiener{"Hallowiener Dog"} --> |Yes| Encounter
    Hallowiener --> |No| SuperLikely

    SuperLikely{"Superlikely available<br>and conditions satisfied"} --- |Yes| SuperlikelyNote["Equal chance of encountering multiple satisfied superlikelies"] --> Encounter
    SuperLikely --> |No| ProtoPack

     subgraph "Zone Overrides"
        ZoneOverride2Note["Not a &quot;true&quot; wandering monster.<br>This is a special exception that has higher priority"]
        ProtoPack[Protopack Ghost]
    end
    ProtoPack --> Wanderers
    Wanderers{Wanderer Due?}
    Wanderers --> |Yes| VHS
    Wanderers --> |No| Kramco

    %% Wanderer Priority
    subgraph "Wanderer Priority"
        VHS[Spooky VHS Tape] -->
        RubberSpider[Rubber Spider] -->
        FeastOfBoris[Feast of Boris] -->
        Club[Club into next week] -->
        Saber[Saber Friends] -->
        TimeSpinner[Time-Spinner Prank] -->
        VotingBooth[Vote Monster] -->
        Digitize[Digitize] -->
        Wink[Reanimator/Angel] -->
        Enamorang -->
        Nemesis[Nemesis Quest Thug] -->
        EDLMB[El Dia De Los Muertos]
    end
    EDLMB --> Encounter

    Kramco{Kramco Goblin} --> |Yes| Encounter
    Kramco --> |No| Hipster

    Hipster{Hipster/Goth} --> |Yes| Encounter
    Hipster --> |No| JuneCleaver

    JuneCleaver{June Cleaver<br>Daydream} --> |Yes| Encounter
    JuneCleaver --> |No| MapMon

    MapMon{Map the<br>Monsters} --> |Yes| Encounter
    MapMon --> |No| Peridot

    Peridot{Peridot} --> |Yes| Encounter
    Peridot --> |No| NcForce

    NcForce{Non-combat Forced} --> |Yes| Encounter
    NcForce --> |No| RollEncounter


    subgraph "Zone Encounter Selection"
        RollEncounter{Roll 1d100<br>against zone combat rate}
        RollEncounter --Combat--> AnyCombats
        RollEncounter ---> |Non-combat| AnyNonCombats

        AnyNonCombats{Any non-combats available?}
        AnyNonCombats ---> |Yes| RollNonCombat
        AnyNonCombats ---> |No| AnyCombats

        RollNonCombat[Roll for NC]
        RollNonCombat --> NonCombatInQueue{Rolled NC in queue?}
        NonCombatInQueue --> |Yes| NonCombatRejection{Roll for rejection}
        NonCombatInQueue --> |No| EncounterSelected
        NonCombatRejection --> |"Rejected (75%)"| RollNonCombat
        NonCombatRejection --> |"Accepted (25%)"| EncounterSelected

        AnyCombats{Any combats available?}
        AnyCombats --> |Yes| RollCombat
        AnyCombats --> |No| Tumbleweed --> EncounterSelected

        RollCombat[Roll for Combat]
        RollCombat --> Olfacted{Olfacted?}
        Olfacted --> |Yes| EncounterSelected
        Olfacted --> |No| CombatInQueue{Rolled combat in queue?}
        CombatInQueue --> |Yes| CombatRejection{Roll for rejection}
        CombatInQueue --> |No| EncounterSelected
        CombatRejection --> |"Accepted (25%)"| EncounterSelected
        CombatRejection --> |"Rejected (75%)"| RollCombat

        EncounterSelected[Encounter selected from zone]
    end

    EncounterSelected --> Encounter

    Encounter[That's your encounter!]